/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        outline: '#6d758c',
        'on-surface': '#dee5ff',
        'on-tertiary-fixed-variant': '#003580',
        'on-tertiary': '#001d4e',
        'on-secondary-fixed-variant': '#591bdc',
        'on-primary': '#005762',
        'primary-dim': '#00d4ec',
        'on-tertiary-container': '#000000',
        'on-primary-container': '#004d57',
        'surface-container': '#0f1930',
        'tertiary-dim': '#0f6df3',
        'inverse-on-surface': '#4d556b',
        'surface-container-low': '#091328',
        'surface-tint': '#81ecff',
        'tertiary-container': '#2778fe',
        'on-secondary-container': '#e4daff',
        'tertiary-fixed': '#8eafff',
        'error-container': '#9f0519',
        'surface-container-high': '#141f38',
        'surface-container-highest': '#192540',
        'on-primary-fixed-variant': '#005762',
        'on-tertiary-fixed': '#00163d',
        'outline-variant': '#40485d',
        'inverse-primary': '#006976',
        'surface-dim': '#060e20',
        'tertiary-fixed-dim': '#77a1ff',
        secondary: '#a68cff',
        'primary-fixed-dim': '#00d4ec',
        'secondary-fixed-dim': '#cabaff',
        'primary-fixed': '#00e3fd',
        tertiary: '#6e9bff',
        'on-background': '#dee5ff',
        'on-surface-variant': '#a3aac4',
        'surface-variant': '#192540',
        'secondary-dim': '#7e51ff',
        background: '#060e20',
        'on-secondary-fixed': '#3b00a0',
        'inverse-surface': '#faf8ff',
        'error-dim': '#d7383b',
        'primary-container': '#00e3fd',
        'surface-bright': '#1f2b49',
        'on-secondary': '#25006b',
        'surface-container-lowest': '#000000',
        'on-error-container': '#ffa8a3',
        'on-error': '#490006',
        'secondary-fixed': '#d8caff',
        primary: '#81ecff',
        surface: '#060e20',
        error: '#ff716c',
        'on-primary-fixed': '#003840',
        'secondary-container': '#591adc',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        // Use Tailwind defaults — do NOT override lg/xl/full here
        // as that breaks pill shapes, avatars, and card corners.
        // If you want smaller default base radius, override only DEFAULT.
        DEFAULT: '0.375rem', // 6px — a sensible base (Tailwind default is 4px)
      },
    },
  },
  plugins: [],
}
