/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        outline: '#525252',
        'on-surface': '#f0f0f0',
        'on-tertiary-fixed-variant': '#333333',
        'on-tertiary': '#121212',
        'on-secondary-fixed-variant': '#444444',
        'on-primary': '#1a1a1a',
        'primary-dim': '#a3a3a3',
        'on-tertiary-container': '#ffffff',
        'on-primary-container': '#ffffff',
        'surface-container': '#0d0d0d',
        'tertiary-dim': '#8a8a8a',
        'inverse-on-surface': '#262626',
        'surface-container-low': '#050505',
        'surface-tint': '#e5e5e5',
        'tertiary-container': '#262626',
        'on-secondary-container': '#e5e5e5',
        'tertiary-fixed': '#d4d4d4',
        'error-container': '#4a0006',
        'surface-container-high': '#141414',
        'surface-container-highest': '#1a1a1a',
        'on-primary-fixed-variant': '#262626',
        'on-tertiary-fixed': '#0a0a0a',
        'outline-variant': '#333333',
        'inverse-primary': '#404040',
        'surface-dim': '#050505',
        'tertiary-fixed-dim': '#a3a3a3',
        secondary: '#a3a3a3',
        'primary-fixed-dim': '#a3a3a3',
        'secondary-fixed-dim': '#a3a3a3',
        'primary-fixed': '#e5e5e5',
        tertiary: '#b3b3b3',
        'on-background': '#f0f0f0',
        'on-surface-variant': '#a3a3a3',
        'surface-variant': '#1a1a1a',
        'secondary-dim': '#737373',
        background: '#050505',
        'on-secondary-fixed': '#1a1a1a',
        'inverse-surface': '#f0f0f0',
        'error-dim': '#991b1b',
        'primary-container': '#e5e5e5',
        'surface-bright': '#262626',
        'on-secondary': '#1a1a1a',
        'surface-container-lowest': '#000000',
        'on-error-container': '#ffb4ab',
        'on-error': '#690005',
        'secondary-fixed': '#e5e5e5',
        primary: '#d4d4d4',
        surface: '#050505',
        error: '#ffb4ab',
        'on-primary-fixed': '#1a1a1a',
        'secondary-container': '#262626',
      },
      fontFamily: {
        headline: ['Syne', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        manrope: ['Syne', 'sans-serif'],
      },
      borderRadius: {
        // Use Tailwind defaults — do NOT override lg/xl/full here
        // as that breaks pill shapes, avatars, and card corners.
        // If you want smaller default base radius, override only DEFAULT.
        DEFAULT: '0.375rem', // 6px — a sensible base (Tailwind default is 4px)
      },
    },
  },
  plugins: [],
}
